site_name: MkDocs を Azure Static Web Apps にデプロイしよう
nav:
  - Home: index.md
  - MkDocs をセットアップする: mkdocs-setup.md
  - Azure のセットアップ: azure-setup.md
theme: material
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - admonition
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
